### PR TITLE
New assets

### PR DESCRIPTION
**Pull request by superjohan**
Replaced header and icons.

### CODE REVIEW

**Comment by alepar666** [comment]
Only issue on the banner, clearly there is a visual issue between background colors.
Will speak with the designer and come back with a new one (IMHO previous one was better)

**Comment by superjohan** [comment]
I didn't even run it, I just changed the assets. :) Looking at `MainView.xib`, the frame for the header is wrong. Fixing.

**Comment by superjohan** [comment]
@alepar666: the layout should be better now.

**Comment by superjohan** [comment]
Simulator Screen Shot - iPhone 8 - 2021-01-17 at 15 31 44

**Review by alepar666 — APPROVED** [review]

**Pull request merged**
