### PR TITLE
Extract the audio player to its own class

### PR DESCRIPTION
**Pull request by superjohan**
The player is now written in Swift. This is done in anticipation of CarPlay support, which will require exactly this if we want it to work properly. I also reworked the UI code quite extensively. It is now much simpler and straightforward. There may be some bugs I haven't run into yet, though.

`MainViewController` is so small now that it could also be rewritten in Swift, although I'd rather do that in a separate PR. It would make `IFMPlayer` a bit more ergonomic to use, since we could use associated types in enums and all that jazz.

Would either @alepar666 or @tijmenb be interested in reviewing/testing this?

### CODE REVIEW

**Review by alepar666 — APPROVED** [review]
I don't really know Swift language so my review is based on general principles but I will be for sure in for the testing

**Comment by tijmenb** [comment]
Great! Will take a look at this tonight!

**Review by tijmenb — APPROVED** [review]
This looks good. Ran this on the simulator iPhone 15 and a real iPhone 11. I tested the playback buttons, remote control, simulated the tracks service being down and the streaming server being down, and it all works as expected 🚀

**Comment by superjohan** [comment]
Great! I'll merge this and prepare a release shortly. I started working on converting the view controller to Swift as well, with all that entails, but I'm not sure it'll make it just yet. Just that the ObjC stuff in the player bothers me now. :)

**Pull request merged**
