### PR TITLE
graphic changes

### PR DESCRIPTION
**Pull request by alepar666**
pretty simple modifications, updated the channels graphic with current website's and dynamic text color / font
mocked play button inside banner
note: graphics for now are manually made by me, they could be replaced with better ones arriving later in time, but the structure could be this one.
regarding the scrolling text, do you think there is a need to change the current coordinate positioning method (the one in the comments is mentioned as FIXME) I tested with different iphone version simulator and indeed there is some slight difference... that could be really something to fix.

### CODE REVIEW

**Comment by alepar666** [comment]
New graphics, custom font for scrolling text, official json file hosted on IFM for radio channels url and api for getting "playing now" info.

**Comment by superjohan** [comment]
I did a rebase which apparently totally fucked up this PR. Sorry. I'll open up a new one. For future reference, never use the main branch for pull requests. :)

**Comment by alepar666** [comment]
No worries, I am so worst than you !
Just to be sure you’re aligned with the latest graphics and code, I have all in my master branch,
If I need something to do in order to allow you to get that let me know, otherwise you can start directly from that instead of the “update” branches...

**Comment by superjohan** [comment]
I merged the first PR. Opened a new PR with the changes from this one: https://github.com/superjohan/ifm/pull/3

I had some conflicts, hope I didn't fuck everything up.

**Pull request closed without merging**
