### PR TITLE
Integration without breaking

### PR DESCRIPTION
**Pull request by alepar666**
So this is the best I managed to integrate.
If I run your last  code I lost many changes (font, position of the elements, scrolling text position, etx)
So I integrated what Icould and recommitted in my master branch.
Also, the deprecated notifications I fixed them while ago, adding also new  set of icon for each iphone model.

Try to see if what I am committing makes sense to you, it  can be that I override something, but in my version all is still working  fine

### CODE REVIEW

**Comment by superjohan** [comment]
Hmm, when I run the code in https://github.com/superjohan/ifm/pull/3, everything looks fine to me, I think.

**Comment by superjohan** [comment]
For reference:

Simulator Screen Shot - iPhone 12 mini - 2021-01-14 at 13 24 14

Also, this PR is once again from the master branch. You need to put your changes in a branch that's not master.

**Comment by superjohan** [comment]
Also the last commit in this PR actually _reverts_ all the changes I made. :)

**Comment by alepar666** [comment]
I’m sorry. I’m lost. But I think the main issue is that you didn’t merged
my master where I had the last code, with my last pull request I included
this and now you should be able to repeat (I guess again) your fixes.

Il giorno gio 14 gen 2021 alle 12:26 Johan Halin <notifications@github.com>
ha scritto:

**Comment by superjohan** [comment]
No, I did, in https://github.com/superjohan/ifm/pull/3 - please take a look, it's identical to this PR except that it also contains changes I've made. I rebased, i.e. placed all your `master` commits on top of the first PR that I merged. That's what also ended up wrecking your fork, unfortunately.

**Pull request closed without merging**
